depromeet/antoon_web

.eslintrc.json

⚙️ eslint end of line 룰 추가

---

components/Row.tsx
components/detail/category/Category.style.tsx
components/detail/tabs/Tabs.style.tsx
components/image/Thumbnail.style.tsx
domains/webtoon/detail/Detail.style.tsx
domains/webtoon/detail/Detail.tsx
package.json
styles/globalstyles/GlobalStyle.tsx

- 린트가 깨져서 이 상태로 작업하면 풀리퀘에 덮어씌워지기 때문에 픽스하였습니당.
- `yarn lint-fix` 후 문제 없는 것을 확인
- 허스키에서 기존 스크립트를 사용하도록 변경
```
"lint-staged": {
"./**/*.{js,ts,tsx}": [
"yarn lint-fix:prettier",
"yarn lint-fix:stylelint",
"yarn lint-fix:eslint"
]
```

⚙️ [프로젝트 세팅] 린트 픽스

---

components/charts/Charts.tsx
components/charts/chart-utils.ts
components/charts/composables/Chart_Options.tsx
components/charts/composables/Chart_Visualizer.ts
components/detail/tabs/Tabs.style.tsx
components/detail/tabs/Tabs.tsx
domains/webtoon/detail/Detail.style.tsx
domains/webtoon/detail/Detail.tsx
pages/webtoon/[id].tsx
styles/themes/themes.ts
types/webtoon-type.d.ts

- related issue: #37 #32 
- 상세 컴포넌트 수정
- 내일부터는 댓글 할 예정 
<table>
<tr row='2'>
<td>
</td>
<td>
</td>
</tr>
</table>

:fire:[feature]: Update Detail Main Component

---

components/detail/commentTextInput/CommentTextInput.style.tsx
pages/webtoon/[id].tsx

Signed-off-by: poo <poo1994@hanmail.net>
- 댓글 컴포넌트 스타일 수정사항 반영

:fire:[bug]: Add style ReplyComponent

---

components/image/UserProfile.style.tsx
components/image/UserProfile.tsx
domains/webtoon/detail/Comment.tsx

- 사용자 댓글이 한 줄 이상 넘어갈 때 이미지 크기가 무너지는 현상을 해결했습니다.

🐛 [사용자 프로필 이미지] 크기 변동 문제 해결

---

.github/workflows/deploy.yml
apis/queryKeys.ts
apis/webtoons.ts
domains/webtoon/home/RealTimeChart.tsx
next.config.js
pages/index.tsx
types/webtoon-type.d.ts

웹툰 랭킹 api 연결
랭킹 api 가 아직 완전한 데이터를 주지 않아서 일정하게 랜덤으로 대응했습니다.

✨ [홈  페이지] 웹툰 랭킹 api 연결

---

components/detail/button/BtnFooter.style.tsx
components/detail/button/UpDownBtn.style.tsx

Signed-off-by: choipureum <pooreumsunny@gmail.com>
- 최종 상세 css 마크업 수정
- 웹 화면 지원
- 🥰

:fire:[bug]: Update Detail Footer css 

---

apis/index.ts
apis/queryKeys.ts
apis/webtoons.ts
components/modal/onboard/Modal.tsx
domains/webtoon/home/Genres.style.tsx
domains/webtoon/home/Genres.tsx
next.config.js
pages/_app.tsx
pages/index.tsx
styles/themes/themes.ts

- 장르별 웹툰 수정하였씀당
배포를 위해 일단 머지하겠습니당!!!

✨ [홈 페이지] 장르별 웹툰 수정

---

domains/webtoon/home/Recommendation.stories.tsx
domains/webtoon/home/Recommendation.style.tsx
domains/webtoon/home/Recommendation.tsx

연령대별로 추천해주는 섹션입니당.
- 연령대별 추천 웹툰 마크업 추가
유저 나이대로 표시해줘야하는 건 나중에..

✨ [홈 페이지] 연령대별 추천 웹툰

---

components/ErrorBoundary.tsx
domains/webtoon/home/RealTimeChart.tsx
domains/webtoon/home/WeeklyWebtoons.tsx

클라이언트 사이드 ui 에러가 서버 에러처럼(500) 보여주기 때문에 에러 바운더리 추가했습니다.
https://nextjs.org/docs/messages/client-side-exception-occurred
https://nextjs.org/docs/advanced-features/error-handling

🥅  [에러 처리] 에러 바운더리 추가

---

domains/webtoon/home/Weekly.tsx

피그마와 요일 순서가 맞지 않았습니당.
기존
일 ~ 토
변경요청
월 ~ 일

🩹 [홈 페이지/QA] 요일별 웹툰 요일 순서 변경

---

domains/search/Search.tsx
pages/user/signin.tsx
utils/autoComplete.ts

아래 두 PR 코드 리뷰 내용 반영했습니다!
1. [✨ [사용자 인증] 토큰 값 쿠키 관리 기능 생성](https://github.com/depromeet/antoon_web/pull/83)
2. [🛠 [코드 포맷] 스타일 및 서식 수정](https://github.com/depromeet/antoon_web/pull/85)
항상 코드 리뷰 해주셔서 감사합니다 ✨👍

♻️ [리팩터링] 변수명 수정

---

apis/webtoons.ts
components/charts/composables/Chart_Visualizer.ts
components/detail/category/CategoryCard.tsx
components/detail/category/CategorySlider.tsx
domains/webtoon/detail/Detail.style.tsx
domains/webtoon/detail/Detail.tsx
pages/webtoon/[id].tsx
types/webtoon-type.d.ts
utils/css-util.ts

Signed-off-by: choipureum <pooreumsunny@gmail.com>
=이후=
- 탑승 버튼 페칭 진행
- 차트데이터 api 결정되면 차트관련 데이터 페칭 진행 예쩡 
- 시간되면 리팩토링

:fire:[feature] Add Detail DataFetching

---

pages/_app.tsx

hotjar 추가했습니당
히트맵이나 레코딩 되게 신기하네여..

📦 [프로젝트 세팅] hotjar 추가

---

domains/webtoon/detail/Detail.style.tsx

fix bug css

---

components/detail/button/BtnFooter.style.tsx
components/detail/button/Toast.style.tsx
domains/webtoon/detail/Detail.style.tsx

- 상세 페이지의 스타일린트 에러를 해결했습니다.
- CSS 수정이나 기능 수정은 없고 main 브랜치 배포 오류 해결하기 위해 `yarn lint-fix`만 적용했습니다.

♻️ [상세 페이지] 스타일린트 에러 해결

---

next-sitemap.config.js
package.json
public/robots.txt
public/sitemap-0.xml
public/sitemap.xml
yarn.lock

- build 할 때 Robots, Sitemap 파일 자동 생성할 수 있도록 설정했습니다.
요 부분 해결하기 위해 작업했습니다

🔍️ [SEO] Robots, Sitemap 설정

---

README.md

- report bug, request feature 링크가 7조의 프론트 엔드 리포지토리로 지정이 되어있음.
- 링크 단순 수정

 🐛 [fix] 잘못 지정된 링크 수정

---

components/ErrorBoundary.tsx

- 에러 바운더리 CSS 수정했습니다.
엄청 엄청 사소한 수정 사항 PR입니다 👀

💄 [에러 바운더리] 텍스트 CSS 수정

---

components/layout/Header/Header.tsx
components/layout/Header/HeaderLeftMenu.tsx
components/layout/Header/HeaderRightMenu.style.tsx
components/layout/Header/HeaderRightMenu.tsx
pages/community/topic/[id].tsx
pages/index.tsx

:recycle: [레이아웃] Header 사용자 데이터 API 변경

---

assets/icons/CheckIcon.tsx
components/detail/button/BtnFooter.tsx
components/timecounter/TimeCounter.tsx
components/vote/ChiceVoteItem.tsx
components/vote/ChoiceVoteItem.style.tsx
components/vote/VoteHeader.style.tsx
components/vote/VoteHeader.tsx
domains/community/topic/ChoiceVote.style.tsx
domains/community/topic/ChoiceVote.tsx
domains/community/topic/VoteDetail.tsx

- 초이스 투표 마크업 완료(모달, 투표 헤더 A/B 동일 컴포넌트)
- ⛔️[hotfix]: timecounter
- 투표완료시 마크업 남앗슴당

:fire:[feature]: 초이스 투표 마크업 구현 및 timecounter 버그 fix

---

components/vote/ABVoteItem.tsx

:bug: [투표] 빌드 에러 해결

---

components/modal/vote/Modal.tsx
components/vote/ABVoteItem.style.tsx
components/vote/ABVoteItem.tsx
components/vote/VoteHeader.tsx
domains/community/topic/ABVote.tsx
domains/community/topic/ChoiceVote.tsx
domains/community/topic/VoteDetail.tsx

- 투표 ab/choice api 연동 및 동작 확인
- 연동 끝낫는데 api 프로퍼티 추가 예정으로 수정 이슈 잇음
- 동작 후 모달 닫힘으로 일단 처리 ->  따로 투표 완료 이벤트 필요할듯(ex)토스트)(디자인음슴)
- 일단 위에 이벤트같은거 보다 탑하차가 급해서 윤영님과 최고 우선순위로 먼저 작업하겟음

:fire:[feature]: vote api연동 및 테스트

---

components/button/TagBtn.tsx
domains/community/Community.style.tsx
domains/community/topic/AllTopicCards.style.tsx
domains/webtoon/home/Home.style.tsx
domains/webtoon/home/Home.tsx
domains/webtoon/home/TopicBanners.style.tsx
domains/webtoon/home/TopicBanners.tsx

mvp 2차에 추가된 토픽 배너, 마크업 입니당
토픽 배너의 캐러셀 기능은 추후 적용하겠슴당

✨ [홈] 토픽 배너 및 mvp 2차 마크업

---

components/button/VoteBtn.tsx
components/detail/button/UpDownBtn.tsx
components/detail/commentTextInput/CommentTextInput.style.tsx
components/detail/commentTextInput/CommentTextInput.tsx
components/toast/Toast.tsx
stores/toast.tsx

- 댓글 및 탑하차/ 투표 기능등 미 로그인시 핸들링 추가 및 토스트 적용

[Fix] : 상세 로그인 에러 핸들링 추가

---

apis/queryKeys.ts
apis/topics.ts
apis/webtoons.ts
components/Title.tsx
domains/community/ranks/CommunityRanks.tsx
domains/community/ranks/CommunityRanksCards.tsx
domains/community/topic/AllTopicCards.style.tsx
domains/community/topic/AllTopicCards.tsx
domains/community/topic/TopicCards.style.tsx
domains/community/topic/TopicCards.tsx
domains/community/topic/TopicCategroyButtons.style.tsx
domains/webtoon/home/Home.style.tsx
domains/webtoon/home/Home.tsx
domains/webtoon/home/TopicBanners.style.tsx
domains/webtoon/home/TopicBanners.tsx
domains/webtoon/home/realTimeChart/CharacterJoinButton.tsx
domains/webtoon/home/realTimeChart/RealTimeChart.tsx
domains/webtoon/home/realTimeChart/RealTimeChartCharacters.tsx
domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.style.tsx
domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.tsx
pages/community.tsx
pages/community/ranks.tsx
types/topics-type.d.ts
types/topics-type.ts
types/webtoon-type.d.ts

리뉴얼된 홈과 커뮤니티 페이지에 랭킹과 실시간 차트 전체보기 페이지 추가하였음당
일단 전체발표에 맞춰서 구현위주로 작성해서 코드가 지저분함당... 오늘 밤에 수정해보겠음당

✨ [홈/커뮤니티] 홈 배너 및 웹툰 랭킹 커뮤니티 페이지에서 사용

---

apis/queryKeys.ts
apis/topics.ts
domains/community/topic/AllTopicCards.tsx
types/topics-type.d.ts

[fix]: 최종 merge

---

domains/community/ranks/CommunityRanksCards.tsx
domains/community/topic/AllTopicCards.style.tsx
domains/community/topic/AllTopicCards.tsx
types/webtoon-type.d.ts

토픽별 상세 페이지로 이동 추가
발표 준비위한 pr로 바로 머지하겠음당

✨ [커뮤니티] 토픽 상세 페이지로 이동

---

domains/community/character/CharacterPageCountDown.tsx
domains/community/ranks/CommunityRanks.style.tsx
domains/community/ranks/CommunityRanks.tsx
domains/webtoon/home/Home.style.tsx

[feature]: 실시간 차트 타임카운터 추가

---

domains/community/ranks/CommunityRanks.style.tsx

🐛 [배포] 메인 브랜치 lint 배포 오류 수정

---

components/detail/button/BtnFooter.style.tsx
components/layout/Header/HeaderLeftMenu.tsx
components/layout/Header/HeaderRightMenu.tsx
domains/user/mypage/UserBadge.tsx
domains/user/signup/modal/CoinModal.tsx
domains/webtoon/detail/Comment.style.tsx
pages/index.tsx
pages/user/signin.tsx

- 세부적인 css 값 수정했습니다.
- 회원가입 모달에서 로컬 스토리지를 사용하는 것을 세션 스토리지로 변경했습니다.

🐛 [버그] 세부적인 버그 픽스

---

domains/user/signup/modal/CoinModal.tsx
pages/index.tsx
pages/user/signin.tsx

- Next의 `getServerSideProps`에서 세션 스토리지 값을 설정할 수 없어서 쿠키로 변경했습니다.

🐛 [회원가입] 모달 status 값 변경

---

domains/community/ranks/CommunityRanks.style.tsx
domains/community/ranks/CommunityRanksCards.tsx
domains/community/topic/AllTopicCards.tsx
domains/webtoon/home/Home.style.tsx
domains/webtoon/home/realTimeChart/RealTimeChartCharacters.tsx
domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.tsx
pages/community.tsx

qa 적용된 부분 변경합니다
및 자잘한 디자인 수정하였습니다

🎨 [커뮤니티] qa 마크업 적용

---

domains/community/topic/AllTopicCards.style.tsx
domains/community/topic/AllTopicCards.tsx
domains/webtoon/home/WeeklyWebtoons.tsx
pages/user/signin.tsx

로딩시 화면이동 최소한으로 하였음당
모든 토픽 스켈레톤은 은젠가...

[홈/커뮤니티] CLS 대응

---

components/bar/Bar.tsx
components/modal/detail/Modal.tsx

[fix]: css 디테일 수정 작업

---

apis/queryKeys.ts
apis/webtoons.ts
components/button/FloatingBtn.tsx
components/layout/Header/Header.style.tsx
components/layout/Header/Header.tsx
domains/community/character/CharacterDetailPage.style.tsx
domains/community/character/CharacterDetailPage.tsx
domains/webtoon/home/realTimeChart/RealTimeChartCharacters.tsx
hooks/useScroll.ts
pages/community/character/[id].tsx
types/webtoon-type.d.ts

✨ [인물/커플 상세페이지] 데이터 API 연동

---

domains/webtoon/home/Home.style.tsx
domains/webtoon/home/WeeklyWebtoons.tsx
domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.style.tsx

qa 대응임당
https://app.asana.com/0/1202299457003825/1202529274122589
qa 🚀

[홈] 랭킹 마진 조정

---

domains/community/topic/AllTopicCards.style.tsx
domains/webtoon/home/Home.style.tsx
domains/webtoon/home/realTimeChart/RealTimeChartTitle.tsx
domains/webtoon/home/realTimeChart/RealTimeChartWebtoon.style.tsx
styles/GlobalStyle.tsx

🎨[홈] 배너 마크업 조정

---

components/modal/detail/Modal.style.tsx

Signed-off-by: choipureum <pooreumsunny@gmail.com>
- 웹툰 상세 모달 아이폰 12미니 css 깨짐 현상 수정

[Hotfix]-css 1

---

components/button/VoteBtn.tsx
components/vote/ABVoteItem.tsx
domains/community/topic/ABVote.tsx

[hotfix]: 투표 에러핸들링

---

domains/webtoon/detail/Detail.tsx

[웹툰 상세] 웹툰 상세 단위 변경

---

domains/webtoon/detail/Detail.tsx

[웹툰 상세] 웹툰 상세 단위 대문자로 변경

---

components/bar/Bar.tsx
components/button/FloatingBtn.tsx
components/detail/button/BtnFooter.tsx
components/detail/category/Category.style.tsx
components/vote/ABVoteItem.style.tsx
components/vote/ABVoteItem.tsx
domains/community/topic/AllTopicCards.style.tsx
domains/community/topic/AllTopicCards.tsx
domains/webtoon/home/TopicBanners.tsx
domains/webtoon/home/Weekly.style.tsx
pages/user/signin.tsx

🩹 [QA] QA 반영

---

components/vote/ABVoteItem.tsx
components/vote/ChiceVoteItem.tsx
domains/community/topic/AllTopicCards.tsx
domains/community/topic/TopicCards.tsx
domains/webtoon/detail/Comment.tsx
domains/webtoon/detail/Detail.tsx
types/topics-type.d.ts

api 스펙이 변경되면서 에러가 생기는 부분 처리했습니다. 
센트리 참고
https://sentry.io/organizations/antoon/issues/3390237262/?environment=prd&project=6406864&query=is%3Aunresolved
qa 라 머지하겠습니당

🥅 [에러 핸들링] API 에러 핸들링 추가

---

apis/queryKeys.ts
apis/webtoons.ts
domains/community/character/CharacterDetailPage.style.tsx
domains/community/character/CharacterDetailPage.tsx
domains/community/character/CharacterVoteModal.style.tsx
domains/community/character/CharacterVoteModal.tsx
pages/community/character/[id].tsx

✨ [인물/커플 상세페이지] 인물/커플 탑승하기

---

apis/comments.ts
assets/icons/HeartIcon.tsx
components/button/FavoriteBtn.tsx
components/button/FloatingBtn.tsx
domains/webtoon/detail/Comment.tsx

✨ [댓글] 좋아요 버튼 API 연동

---

components/vote/ChiceVoteItem.tsx

Signed-off-by: choipureum <pooreumsunny@gmail.com>
- 초이스 투표 로그인 에러핸들링

[hotfix]: 초이스 투표 로그인 에러핸들링

---

assets/icons/antcoin_bg_gray.svg
assets/icons/index.ts
components/modal/coin/NotEnoughCoin.style.tsx
components/modal/coin/NotEnoughCoin.tsx
components/modal/vote/Modal.tsx
domains/community/character/CharacterVoteModal.tsx

- 코인 부족할 때 모달 생성했습니다.
- A/B 투표 페이지에서 테스트해야 하는데 지금 무조건 투표 완료로 값이 와서 테스트 못 했습니다..
- 커밋 메시지 영어로 쓴 거 처음인데.. 일부러 그런 건 아니고 갑자기 vscode 터미널에서 한글 입력이 안 먹어서 어쩔 수 없이 영어로 썼습니다 .. 🤔

✨ [모달] 코인 부족할 때 모달 생성

---

apis/user.ts
domains/user/mypage/edit/EditImg.tsx
pages/community/character/[id].tsx
pages/user/mypage/edit.tsx
pages/webtoon/[id].tsx

- 이름 수정 API의 `queryClient.invalidateQueries` key 값 설정 내용 변경했습니다.
- 커밋 메시지 영어로 쓴 거 처음인데.. 일부러 그런 건 아니고 갑자기 vscode 터미널에서 한글 입력이 안 먹어서 어쩔 수 없이 영어로 썼습니다 .. 🤔

🩹 [마이페이지] 이름 수정 API 변경

---

domains/user/mypage/MyPage.style.tsx
domains/user/mypage/edit/EditName.style.tsx
domains/user/mypage/edit/EditName.tsx
pages/user/mypage/edit.tsx

- 프로필 이름 수정에서 사용자가 0글자(최소), 20글자(최대)를 입력했을 때 에러 처리했습니다.

🐛 [마이페이지] 프로필 이름 수정 에러 해결

---

components/vote/ABVoteItem.style.tsx
components/vote/ABVoteItem.tsx

- 아사나 QA 2개 
- AB투표카드, A/B카드 radius값 수정 이슈 해결

:fire:[fix]: QA - [AB투표카드, A/B카드 radius값 수정] 2개 이슈 해결

---

components/detail/button/BtnFooter.style.tsx
components/detail/category/Category.style.tsx
components/detail/category/CategorySlider.tsx
domains/webtoon/detail/Comment.tsx
domains/webtoon/detail/Detail.style.tsx
domains/webtoon/detail/Detail.tsx

- QA 이슈: 슬라이더 padding값 처리, blur width 100% 조절, 렌더처리 이슈 해결

:fire:[fix]: QA - 렌더처리 이슈, 슬라이더 padding이슈 해결

---

.github/workflows/deploy.yml
.github/workflows/deploy_dev.yml
.github/workflows/deploy_stg_and_prd.yml
domains/webtoon/detail/Detail.tsx

빌드가 에러난 채로 메인에 배포된 케이스가 발생해서 PR 생성 시에도 ci/cd를 확인할 수 있게 하였습니다.

🚑 [프로젝트 세팅] PR 생성 시 ci/cd 작동 추가 및 빌드 에러 수정

---

assets/icons/email.svg
components/button/FloatingBtn.tsx

- [QA [프론트/개선] 피드백 버튼 그림자 값 수정](https://app.asana.com/0/1202637499209292/1202660569006987/f) 작업했습니다.

💄 [메인페이지] 피드백 버튼

---

pages/user/mypage.tsx

- 리액트 쿼리의 `status`에서 리액트 `state` 값으로 임시 변경했습니다.
- 코드 리뷰해 주신 내용으로 반영했는데 정상적으로 동작이 잘 안되는 거 같아서 임시로 롤백 했습니다 😭
- 롤백 이후 다시 리액트 쿼리 `status` 사용할 수 있도록 오류 원인 분석해 보겠습니다 🤔
- [이전 작업 PR 링크](https://github.com/depromeet/antoon_web/pull/199)

♻️ [마이페이지] state로 분기 처리

---

apis/comments.ts
apis/queryKeys.ts
domains/webtoon/detail/Comment.style.tsx
domains/webtoon/detail/Comment.tsx
package.json
public/sitemap-0.xml
yarn.lock

related issue: #194, #208
- 댓글 observer 기반 뷰포트 기준 무한스크롤 구현
- 스피너 훌라후프 현상 해결 및 무한 스크롤 부분 스피너 추가

🔥 [feature] : 댓글 observer 기반 무한스크롤 구현, 댓글 QA 스피너 훌라후프 현상 해결

---

domains/community/topic/TopicCards.style.tsx
domains/community/topic/TopicCards.tsx

메인 페이지 개미들의 선택 섹션 항목 클릭 시 토픽 페이지로 이동
https://app.asana.com/0/0/1202698824462951/f

✨ [웹툰 토픽] 메인 페이지 개미들의 선택 섹션 항목 클릭 시 토픽 페이지로 이동
